{% extends 'home/base.html' %}
{% load static %}

{% block content %}
<br>
  <div class="heading text-center display-3">
    Coding Easy
  </div> <br>
  <section class="container mt-3">
    <div class="row">
      <div class="col-sm-12">
        <div class="jumbotron px-3 py-4 px-sm-4 py-sm-5 bg-light rounded-3 mb-3">
          <h1 class="text-center">Exception</h1>
        </div>
  </section>
  <br><br>


  <!-- code and text -->

  <section class="container mt-5">
    <div class="row">
      <div class="col-md-6 col-sm-12">
        <h3 class="text-center">Exception</h3>
        <p class="text-center">
            The <strong>exceptions</strong> occur when something goes wrong, due to incorrect code or input.
            When an exception occurs, the program immediately stops.
            The following code produces the <strong>ZeroDivisionError</strong> exception by trying to divide 7 by 0:<br><br>
            An <strong>exception</strong> is an event, which occurs during the execution of a program that disrupts the normal flow of the program.
            </p><br><br>
            <p>Different exceptions are raised for different reasons.<br>
            <b style="color: red;">Common exceptions:</b><br>
            <b>ImportError:</b> an import fails;<br>
            <b>IndexError:</b> a list is indexed with an out-of-range number;<br>
            <b>NameError:</b> an unknown variable is used;<br>
            <b>SyntaxError:</b> the code can't be parsed properly;<br>
            <b>TypeError:</b> a function is called on a value of an inappropriate type;<br>
            <b>ValueError:</b> a function is called on a value of the correct type, but with an inappropriate value.<br>
        </p>


      </div>
      <div class="col-md-6 col-sm-12">
        <h3 class="text-center">Code</h3>
        <div class="code">
          <pre>
            <code>
                num1 = 7
                num2 = 0
                print(num1/num2)
            </code>
            <div class="col-md-3 col-sm-6">
              <strong>shell</strong>
                Traceback (most recent call last):
                  File "<string>", line 3, in <module>
                <strong>ZeroDivisionError:</strong> division by zero
            </div>
          </pre>
        </div>
      </div>
    </section>
  <br><br>
  
  <section class="container mt-5">
      <div class="row">
      <div class="col-md-6 col-sm-12">
        <h3 class="text-center">Exception Handling</h3>
        <p class="text-center">
            When an exception occurs, the program stops executing.<br>
            To handle exceptions, and to call code when an exception occurs, you can use a <strong>try/except</strong> statement.<br>
            The <strong>try</strong> block contains code that might throw an exception. If that exception occurs,
            the code in the <strong>try</strong> block stops being executed,
            and the code in the <strong>except</strong> block is run. If no error occurs, the code in the <strong>except</strong> block doesn't run.
            <br><br><br><br><br><br><br>
            A try statement can have multiple different except blocks to handle different exceptions.<br>
            Multiple exceptions can also be put into a single except block using parentheses,
            to have the except block handle all of them.
            <br><br><br><br><br><br><br>
            An <strong>except</strong> statement without any exception specified will catch all errors.<br>
            These should be used sparingly, as they can catch unexpected errors and hide programming mistakes.

        </p>

      </div>
      <div class="col-md-6 col-sm-12">
        <h3 class="text-center">Code</h3>
        <div class="code">
          <pre>
                <code>
                    try:
                        num1 = 7
                        num2 = 0
                        print (num1 / num2)
                        print("Done calculation")
                    except ZeroDivisionError:
                        print("An error occurred")
                        print("due to zero division")
                </code>
                <div class="col-md-3 col-sm-6">
                  <strong>shell</strong>
                    An error occurred
                    due to zero division
                </div>
            </pre>
        </div>
        <div class="code">
          <pre>
                <code>
                    try:
                        variable = 10
                        print(variable + "hello")
                        print(variable / 2)
                    except ZeroDivisionError:
                        print("Divided by zero")
                    except (ValueError, TypeError):
                        print("Error occurred")
                </code>
                <div class="col-md-3 col-sm-6">
                  <strong>shell</strong>
                    Error occurred
                </div>
            </pre>
        </div>
        <div class="code">
          <pre>
                <code>
                    try:
                        word = "spam"
                        print(word / 0)
                    except:
                        print("An error occurred")
                </code>
                <div class="col-md-3 col-sm-6">
                  <strong>shell</strong>
                    Error occurred
                </div>
            </pre>
        </div>
      </div>
  </section>
  <br><br>

  <section class="container mt-5">
    <div class="row">
      <div class="col-md-6 col-sm-12">
        <h3 class="text-center">finally</h3>
        <p class="text-center">
            After a <strong>try/except</strong> statement,
            a <strong>finally</strong> block can follow. It will execute after the <strong>try/except</strong> block,
            no matter if an exception occurred or not.
        </p>

      </div>
      <div class="col-md-6 col-sm-12">
        <h3 class="text-center">Code</h3>
        <div class="code">
          <pre>
                <code>
                    try:
                        print("Hello")
                        print(1 / 0)
                    except ZeroDivisionError:
                        print("Divided by zero")
                    finally:
                        print("This code will run no matter what")
                </code>
                <div class="col-md-3 col-sm-6">
                  <strong>shell</strong>
                    Hello
                    Divided by zero
                    This code will run no matter what
                </div>
            </pre>
        </div>
      </div>
  </section>
  <br><br>

  <section class="container mt-5">
    <div class="row">
      <div class="col-md-6 col-sm-12">
        <h3 class="text-center">else</h3>
        <p class="text-center">
            The <strong>else</strong> statement can also be used with <strong>try/except</strong> statements.<br>
            In this case, the code within it is only executed if no error occurs in the <strong>try</strong> statement.
        </p>

      </div>
      <div class="col-md-6 col-sm-12">
        <h3 class="text-center">Code</h3>
        <div class="code">
          <pre>
                <code>
                    try:
                        print(1)
                    except ZeroDivisionError:
                        print(2)
                    else:
                        print(3)

                    try:
                        print(1/0)
                    except ZeroDivisionError:
                        print(4)
                    else:
                        print(5)
                </code>
                <div class="col-md-3 col-sm-6">
                  <strong>shell</strong>
                  1
                  3
                  4
                </div>
            </pre>
        </div>
      </div>
  </section>
  <br><br>

  <section class="container mt-5">
    <div class="row">
      <div class="col-md-6 col-sm-12">
        <h3 class="text-center">Raising Exceptions</h3>
        <p class="text-center">
            You can throw (or raise) exceptions when some condition occurs.<br>
            For example, when you take user input that needs to be in a specific format,
            you can throw an exception when it does not meet the requirements.<br>
            This is done using the <strong>raise</strong> statement.
            <br><br><br><br><br>
            Exceptions can be raised with arguments that give detail about them.
        </p>

      </div>
      <div class="col-md-6 col-sm-12">
        <h3 class="text-center">Code</h3>
        <div class="code">
          <pre>
                <code>
                    num = 102
                    if num > 100:
                    raise <strong>ValueError</strong>
                </code>
                <div class="col-md-3 col-sm-6">
                  <strong>shell</strong>
                  File "<string>", line 3
                  raise ValueError
                  ^
                  <strong>IndentationError:</strong> expected an indented block
                </div>
            </pre>
        </div>
        <div class="code">
          <pre>
                <code>
                    name = "123"
                    raise NameError("Invalid name!")
                </code>
                <div class="col-md-3 col-sm-6">
                  <strong>shell</strong>
                  Traceback (most recent call last):
                    File "<string>", line 2, in <module>
                  <strong>NameError:</strong> Invalid name!
                </div>
            </pre>
        </div>
      </div>
  </section>
  
  <br><br>
  <section class="container mt-5">
    <div class="row">
      <div class="col-md-6 col-sm-12">
        <h3 class="text-center">Common exceptions:</h3>
        <p class="text-center">
            <strong>ImportError:</strong> an import fails;<br>
            <strong>IndexError:</strong> a list is indexed with an out-of-range number;<br>
            <strong>NameError:</strong> an unknown variable is used;<br>
            <strong>SyntaxError:</strong> the code can't be parsed properly;<br>
            <strong>TypeError:</strong> a function is called on a value of an inappropriate type;<br>
            <strong>ValueError:</strong> a function is called on a value of the correct type, but with an inappropriate value.<br>
        </p>
      </div>
  </section>
  <br><br>

{% endblock content %}
